jobs:
  - employer: "Clarity Software Solutions"
    position: "DevOps Engineer (Full Time)"
    time: "May 2019 - Present"
    details: |
      - Developing custom automation solutions through the use of Docker containers, Bash scripts, and NodeJS apps, saving approximately three man-hours per day.
      - Understanding and automating processes to run Git commands to prepare our daily build packages, automating PHI scrubs in our lower environments, and automatically parsing and reporting commonly made errors in various types of files to our change control team.
      - Experimenting with AWS Lambda in order to build a unified toolkit for our developers to both use and contribute to.
      - Participating in discussions with senior engineers to both plan a digital transformation (a new version of our app and a cloud migration) and about company wide development standards in order to promote automation.
      - Packaging and verifying all shell scripts, cron updates, and SQL scripts for daily production migrations.
      - Watching for patterns in all of our migrations and environments in order to bring problems to light for my team to solve.
      - Completing code, shell script, and SQL migrations to our lower environments as needed throughout the day.
  - employer: "NewHaven.io (Non-Profit)"
    position: "President, Member Board of Directors (Volunteer)"
    time: "November 2018 - Present"
    details: |
      - Organizing events around the city for our members to network and learn new technology skills.
      - Partnering with other technology and non-profit focused organizations to help connect and align groups and individuals.
      - Creating a stronger tech and startup minded community by fostering a culture of creation and experimentation.
      - Managing a team of developers to create and launch a new website for the group. (https://newhaven.io)
  - employer: "Administrative Office (AO) of the United States Courts"
    position: "Software Developer - Temporary Duty Assignment (Shared Time)"
    time: "August 2018 - April 2019"
    details: |
      - Transitioned the Judicial Dashboard to work on an on-premise OpenShift/GlusterFS solution, cutting the deployment time down by 99.17%. This involved converting a single server buildout to a Docker solution to allow multiple developers to work concurrently on their local machines followed by another conversion to Kubernetes to facilitate an efficient rollout to 34 courts in the next six months.
      - Created, maintained, and provided enhancements to the codebase for a web application that automates the daily "getting up to speed" work for District Judges across the country, saving roughly an hour’s worth of time per judge every morning.
      - Collaborated with a remote team of engineers in D.C. to test the scalability of OpenShift for use by other judiciary development teams. This platform is now in the process of being elevated to being a national resource.
      - Communicated with the national IT Security Office to scan images and engineer solutions to remediate findings. held partially in the Hartford courtrooms.
      - Interfaced with District Judges and users in the pilot courts testing the Judicial Dashboard to better understand user needs.
      - Coordinated with cross-functional stakeholders in the AO to align all teams in a common strategic direction.
  - employer: "United States District Court, District of Connecticut"
    position: "Programmer (Full Time)"
    time: "March 2017 - April 2019"
    details: |
      - Transitioned in-house legacy applications to container based architectures with Docker for easier development and deployment. The ability to develop more quickly lead to a partnership with the Case Management Solutions Office in D.C., the hiring of part time developers, and a speedier rollout of the Judicial Dashboard product.
      - Experimented with modern web technologies like Vue.js, Node, and Webpack to lay the groundwork of modernizing the tech stack of the Judicial Dashboard project in order to better source talent for a nationwide rollout.
      - Communicated with developers across the judiciary about emerging technologies that could overhaul the core applications used by districts across the country. That combined advocacy led to a container focused overhaul of the organization's core product offerings and a judiciary-wide OpenShift hosting environment that the District of Connecticut is currently piloting.
      - Implemented an iPad fleet and MachForm solution to shorten the process of gathering information from potential jurors, normalizing the data, and getting it into the hands of attorneys in high profile cases, by 92.5%.
      - Developed a touchscreen jury sign in kiosk to undercut the cost of Xerox’s proposed product, to be used in courthouses nationwide, by ~85%.
      - Coordinated with the district's Security Officer to keep various web servers patched and secure.
  - employer: "LearnToProgram.TV"
    position: "Developer in Residence / Instructor (Part Time)"
    time: "June 2017 - August 2018"
    details: |
      - Kept up with the bleeding edge of the web technology horizon to help set technical direction for LTP's courses and library.
      - Developed an eLearning course titled "Intro to Server Administration" that was distributed across multiple channels (including Udemy, Packt, and Safari).
      - Wrote an article/workshop for the LearnToProgram.TV Magazine titled "The Future Is Docker".
      - Instructed and mentored students in the Framework Web Development Bootcamp, both in-person and online.
  - employer: "United States District Court, District of Connecticut"
    position: "Programmer / Analyst (Full Time)"
    time: "May 2015 - March 2017"
    details: |
      - Created full stack LAMP and Ruby on Rails web applications to automate workflows for HR and Operations. Communications involved in on and off boarding employees was cut by over 40% due to streamlining the process by which system access privileges are requisitioned and assigned.
      - Managed Red Hat servers running IBM Informix and US District Court CM/ECF (our docketing application) instances and prepared for our district's early adopter NextGen CM/ECF upgrade.
      - Crafted complex, multi table queries to generate reports that allowed Magistrate and District Judges on the CM/ECF Committee to decide which nature of suit case types needed to be optimized to abide by the Speedy Trial Clause.
projects:
  - name: "Blue Albums - Work In Progress"
    year: "2019"
    description: "Building a website to keep track of what my friends and I refer to as “blue albums,” or albums that anyone can listen to in their entirely. It was initially built with Vue to learn the framework but I’m porting it to GatsbyJS in order to learn for a different side project."
    technologies: "Vue.js, JavaScript, NodeJS. Transitioning to GatsbyJS."
    github: "https://github.com/Quinncuatro/blue-albums"
    dockerhub: "null"
  - name: "DEVC Webpack Playground"
    year: "2018"
    description: "Experimenting folding Vue.js, Node, and WebPack into a containerized Lucee (open source ColdFusion) and MySQL environment that’s used in the judiciary. The end goal is to spur a modernization effort of our tech stacks across the country."
    technologies: "Vue.js, ColdFusion, Shell, JavaScript, Docker, Node, Webpack, MySQL."
    github: "https://github.com/Quinncuatro/DEVC_Webpack_Playground"
    dockerhub: "null"
  - name: "SLAter "
    year: "2018"
    description: "Programmed a Raspberry Pi to monitor my DeskPro queue and alert me via external speakers when I have a new ticket assigned to me. This workflow was also used to remind a coworker to drink water and cure his gout."
    technologies: "JavaScript, Node, MySQL, Raspberry Pi."
    github: "https://github.com/Quinncuatro/SLAter"
    dockerhub: "null"
  - name: "US Webtranet"
    year: "2017"
    description: "Built a containerized intranet framework for federal agencies. It was presented and used as a Docker technical demo in a nationwide video conference call to other judiciary developers in January of 2017."
    technologies: "Ruby, Rails, SQLite, Draft U.S. Web Design Standards, Docker."
    github: "https://github.com/Quinncuatro/us_webtranet"
    dockerhub: "https://hub.docker.com/r/quinncuatro/us_webtranet/"
  - name: "Digital Signage"
    year: "2017"
    description: "Developed a responsive digital signage system to let competitors in the 2017 National High School Mock Trials Championship know their various courtroom assignments across the Hartford courthouse when new rounds were posted."
    technologies: "JavaScript, Meteor, MongoDB."
    github: "https://github.com/Quinncuatro/signage"
    dockerhub: "null"
presentations:
  - talk: "Leading a Digital Transformation at the Speed of Government"
    conference: "DevOpsDays Austin 2020"
    location: "Austin, TX"
    date: "May 2020"
    video: "null"
  - talk: "Leading a Digital Transformation at the Speed of Government"
    conference: "DevOpsDays Seattle 2020"
    location: "Seattle, WA"
    date: "POSTPONED 2020"
    video: "null"
  - talk: "Leading a Digital Transformation at the Speed of Government"
    conference: "DevOpsDays Hartford 2019"
    location: "Hartford, CT"
    date: "October 2019"
    video: "https://youtu.be/FbEm8wF9CKM?t=308"
  - talk: "Leading a Digital Transformation at the Speed of Government"
    conference: "Google Developers Group DevFest 2019"
    location: "New Haven, CT"
    date: "September, 2019"
    video: "null"
  - talk: "Judicial Dashboard - Dashboard View of Court Operations"
    conference: "U.S. District Courts, IT Conference West"
    location: "Phoenix, AZ"
    date: "August 2018"
    video: "null"
  - talk: "Judicial Dashboard - Dashboard View of Court Operations"
    conference: "U.S. District Courts, District Operational Practices Forum"
    location: "Minneapolis, MN"
    date: "May 2018"
    video: "null"
  - talk: "Intro to DevOps Workshop"
    conference: "Google Developers Group DevFest 2017"
    location: "New Haven, CT"
    date: "November 2017"
    video: "null"
  - talk: "US Webtranet"
    conference: "U.S. District Courts, Collaborative Applications Development (CAD) Developer’s Forum"
    location: "Webex"
    date: "January 2017"
    video: "null"
  - talk: "Human Resources Organizer (HRO)"
    conference: "U.S. District Courts, District Operational Practices Forum"
    location: "Orlando, FL"
    date: "September 2016"
    video: "null"
podcasts:
  - title: "Episode 22: NewHaven.IO"
    show: "Between Two Rocks"
    date: "August 2019"
    description: "Steve and Henry from NewHaven.IO join us to talk about the New Haven tech community, how to get into the tech scene, and what our most hated programming languages are."
    link: "https://betweentworocks.com/episode-22-newhaven-io/"
  - title: "Episode 101: The Water Cooler of New Haven Tech"
    show: "CT Startup Podcast"
    date: "February 2019"
    description: "Introducing NewHaven.io — The water cooler of the New Haven tech scene. The creators’ ultimate goal is to bring a human element to the New Haven tech scene by creating a unified community for the people working within it. They explain to us how the current local tech scene features an expansive catalog of different types of tech and how they are working to bring this wide variety of people together."
    link: "https://ctstartup.com/2019/02/26/episode-101-the-water-cooler-of-new-haven-tech/"